### ISSUE TITLE
Update hackage/stackage version

### ISSUE THREAD

**Issue by gromakovsky** [TokTok/hs-msgpack-binary#12]
Hackage version doesn't contain commit which adds `MessagePack` instance for `Either` as well commit for `Void` by @Martoon-00. They are very useful, so it would be cool to see them on hackage ASAP.

**Comment by iphydf** [comment]
Travis CI seems to have some issues. I'll push the new version to hackage as soon as Travis is happy, and the PR is approved.

**Comment by gromakovsky** [comment]
Got it, thanks for this information.
