### ISSUE TITLE
Maybe should result in ObjectNil OR ObjectXXX

### ISSUE THREAD

**Issue by SX91** [TokTok/hs-msgpack-binary#17]
This case is special and IMO should be implemented this way. Otherwise this realization will be useful for Haskell to Haskell communications only.

Original `msgpack` package instantiated it like that, so why did you change that?

**Comment by SX91** [comment]
https://github.com/TokTok/hs-msgpack-rpc/blob/master/src/Network/MessagePack/Server/Basic.hs#L170
This won't work with other MessagePack-RPC implementations. Because unset error or result should be `Nil`, not an empty array.

**Comment by iphydf** [comment]
@martoon-00: what do you think about this?

**Comment by SX91** [comment]
`Maybe` instance can't be fixed. So don't mind the first message.
The situation described in the second message is fixed in https://github.com/TokTok/hs-msgpack/pull/18.

**Comment by iphydf** [comment]
Anything left to do here?

**Comment by SX91** [comment]
Maybe add `Option a = Some a | None` and somehow forbid nesting, I don't know.
