### ISSUE TITLE
add to stackage

### ISSUE THREAD

**Issue by sboosali** [TokTok/hs-msgpack-binary#4]
could help `call-haskell-from-anything` get on stackage.

**Comment by iphydf** [comment]
Hi, that seems like a good idea, but I have no experience with stack/stackage. Would you like to contribute a stack config file?

**Comment by sboosali** [comment]
Sure! I use stack, I've never added a package to stackage. 

For the stack.yaml, I'll download it and try to get the build.

For stackage, the "contract" with the author is that, whenever your package fails to build, you update your bounds or modify the dependency, within the week (Or something like that). You seem to be actively developing your package, and I tend to do this anyway for my own packages, and furthermore it's like an enormous continuous integration service shared by the ecosystem, so shouldn't be much of a burden.

**Comment by iphydf** [comment]
Done.

**Comment by sboosali** [comment]
Cool. By the way, I couldn't get the tests to build with lts7 (Quickcheck dropped instances for long tuples or something?). But then I got distracted with another project :-)

**Comment by iphydf** [comment]
I think those were added in a newer version. We can fix that by dropping support for long tuples as well, or having an `#if` checking for QC version.
