### ISSUE TITLE
Take backward compatibilty seriously and apply sementic versioning.

### ISSUE THREAD

**Issue by aloiscochard** [TokTok/hs-msgpack-binary#45]
You broke compatibility multiple times on minor release, this is pretty bad.

Plus, you remove `Object`, `Get` and `Put` from the public module and I really don't see the reason (could this be explained in a changelog maybe?).

It's enough for me, i decided to use `packer-messagepack` instead.

https://hackage.haskell.org/package/packer-messagepack

**Comment by iphydf** [comment]
Semantic versioning strips leading zeroes, i.e. 0.0.2 is a breaking change from 0.0.1. We haven't done a 0.1.0 release yet, because we're still playing with the API. Once 0.1.0 is out, all 0.1.x releases will be API-compatible.
