### ISSUE TITLE
Think whether `groom` is actually needed

### ISSUE THREAD

**Issue by maksbotan** [TokTok/hs-msgpack-binary#71]
Hi.

`data-msgpack` depends on the package `groom`, which is used only in the `msgpack-parser` executable. `groom` is a heavy dependency since it pulls in `haskell-src-exts`.

Can you get away without `groom`? I suppose it's a too high price to pay for exactly one usage.

**Comment by iphydf** [comment]
Does it help if we make the executable optional? That way if you depend on the library, you don't get haskell-src-exts into your dependency tree.
